#!/usr/bin/env python3
"""Debug script to check the generated JavaScript"""

import json

# Copy of KNOWN_QA_PATTERNS from agent.py
KNOWN_QA_PATTERNS = {
    'years of experience': '3.8 Years',
    'months of experience': '46',
    'total experience': '3.8 Years',
    'overall experience': '3.8 Years',
    'year of exp': '3.8 Years',
    'current salary': '23 LPA',
    'expected salary': '30 LPA',
    'current ctc': '23 LPA',
    'expected ctc': '30 LPA',
    'monthly salary': '191667',
    'expected annual ctc': '30 LPA',
    'current annual ctc': '23 LPA',
    'phone number': '7905828880',
    'mobile number': '7905828880',
    'email address': 'siddhant3646@gmail.com',
    'current location': 'Noida',
    'current city': 'Noida',
    'preferred location': 'Noida, Delhi NCR, Bangalore, Hyderabad, Mumbai, Pune',
    'current employer': 'Everbridge',
    'current company': 'Everbridge',
    'previous company': 'Fiserv',
    'notice period': '15 days',
    'serving notice': 'Yes',
    'graduation year': '2022',
    'cgpa': '8.51',
    'percentage': '85',
    'degree': 'B.Tech Computer Science',
    'college name': 'VIT Bhopal University',
    'linkedin url': 'https://www.linkedin.com/in/siddhant3646',
    'github url': 'https://github.com/siddhant3646',
    'willing to relocate': 'Yes',
    'work authorization': 'Yes',
    'legally authorized': 'Yes',
    'background check': 'Yes',
    'drug test': 'Yes',
    'remote work': 'Yes',
    'hybrid work': 'Yes',
    'visa sponsorship': 'No',
    'require sponsorship': 'No',
    'programming languages': 'Java, Python, JavaScript',
    'technical skills': 'Java, Spring Boot, React, AWS, Docker',
    'primary competencies': 'Full Stack Development, Cloud Architecture, System Design',
    'top competencies': 'Full Stack Development, Cloud Architecture, System Design',
    'core competencies': 'Full Stack Development, Cloud Architecture, System Design',
    'key skills': 'Java, Spring Boot, React, AWS, Microservices',
    'top 3 primary competencies': 'Full Stack Development, Cloud Architecture, System Design',
    'face to face interview': 'Yes',
    'f2f interview': 'Yes',
    'available for interview': 'Yes',
    'interested for interview': 'Yes',
    'virtual interview': 'Yes',
    'telephonic interview': 'Yes',
    'interested for f2f interview': 'Yes',
    'available for interview': 'Yes',
    'a': 'Yes',
    'b': 'No',
    'c': 'No',
    'd': 'No',
    'e': 'No',
    'share your ctc': 'Current CTC: 23 LPA, Expected CTC: 30 LPA, Notice Period: 15 Days (Negotiable)',
    'ctc ectc np': 'Current CTC: 23 LPA, Expected CTC: 30 LPA, Notice Period: 15 Days (Negotiable)',
    'ctc and np': 'Current CTC: 23 LPA, Expected CTC: 30 LPA, Notice Period: 15 Days (Negotiable)',
    'ctc,ectc and np': 'Current CTC: 23 LPA, Expected CTC: 30 LPA, Notice Period: 15 Days (Negotiable)',
    'salary range': '23-30 LPA',
    'current salary range': '23 LPA',
    'expected salary range': '30 LPA',
    'annual salary': '2300000',
    'ctc range': '23-30 LPA',
    'expected annual ctc in inr': '3000000',
    'expected annual ctc': '3000000',
    'expected ctc in inr': '3000000',
    'expected ctc inr': '3000000',
    'what is your current annual salary': '2300000',
    'what is your current annual salary?': '2300000',
    'what is your expected annual salary': '3000000',
    'what is your expected annual salary?': '3000000',
    'what is your current salary?': '23 LPA',
    'what is your expected salary?': '30 LPA',
    'what is your current ctc': '23 LPA',
    'what is your current ctc?': '23 LPA',
    'gross salary': '23 LPA',
    'gross current salary': '23 LPA',
    'gross expected salary': '30 LPA',
    'salary expectations': '30 LPA',
    'product based': 'Yes, I have experience working at Everbridge which is a product-based company in the BFSI domain.',
    'bfsi domain': 'Yes, I am currently working at Everbridge in the BFSI (Banking, Financial Services, Insurance) domain with 3.8 years of experience.',
    'previous company': 'Fiserv',
    'worked with everbridge': 'Yes',
    'worked with fiserv': 'Yes',
    'worked at everbridge': 'Yes',
    'worked at fiserv': 'Yes',
    'have you worked with everbridge': 'Yes',
    'have you worked with fiserv': 'Yes',
    'have you worked at everbridge': 'Yes',
    'have you worked at fiserv': 'Yes',
}

if __name__ == '__main__':
    print("KNOWN_QA_PATTERNS loaded successfully")
    print(f"Total patterns: {len(KNOWN_QA_PATTERNS)}")
